#############################################################################
# Makefile for building: ImplicitObjects
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Thu Jun  4 16:30:07 2015
# Project:  ImplicitObjects.pro
# Template: app
# Command: $(QMAKE) -o Makefile ImplicitObjects.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fno-strict-aliasing  -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -std=c++11 -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fno-strict-aliasing  -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib64/qt-3.3/mkspecs/default -I. -I"/users/rsg/mmi/gmtl-0.6.1/build/include/gmtl-0.6.1/" -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = HashTable.h \
		MarchingCubes.h \
		MCTables.h \
		GLData.h \
		Object.h
SOURCES = main.cpp \
		HashTable.cpp \
		MarchingCubes.cpp \
		GLData.cpp \
		Object.cpp
OBJECTS = main.o \
		HashTable.o \
		MarchingCubes.o \
		GLData.o \
		Object.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = ImplicitObjects.pro
QMAKE_TARGET = ImplicitObjects
DESTDIR  = 
TARGET   = ImplicitObjects

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: ImplicitObjects.pro  /usr/lib64/qt-3.3/mkspecs/default/qmake.conf /usr/lib64/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile ImplicitObjects.pro
qmake: 
	@$(QMAKE) -o Makefile ImplicitObjects.pro

dist: 
	@mkdir -p .tmp/ImplicitObjects && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/ImplicitObjects/ && ( cd `dirname .tmp/ImplicitObjects` && $(TAR) ImplicitObjects.tar ImplicitObjects && $(GZIP) ImplicitObjects.tar ) && $(MOVE) `dirname .tmp/ImplicitObjects`/ImplicitObjects.tar.gz . && $(DEL_FILE) -r .tmp/ImplicitObjects

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp GLData.h \
		Object.h \
		MarchingCubes.h \
		HashTable.h

HashTable.o: HashTable.cpp HashTable.h \
		GLData.h

MarchingCubes.o: MarchingCubes.cpp MarchingCubes.h \
		MCTables.h \
		Object.h \
		GLData.h \
		HashTable.h

GLData.o: GLData.cpp GLData.h

Object.o: Object.cpp Object.h \
		GLData.h

####### Install

install:  

uninstall:  

